name: Capture Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # midnight PST

jobs:
  capture:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          export CRANE_USERNAME="${{ github.repository_owner }}"
          export CRANE_PASSWORD="${{ secrets.GITHUB_TOKEN }}"
          hack/capture-images.sh "${{ github.repository }}"
