name: Capture Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # midnight PST

jobs:
  capture:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          REGISTRY="ghcr.io/${{ github.repository }}"
          echo "${GITHUB_TOKEN}" | docker login "${REGISTRY}" --username "${{ github.repository_owner }}" --password-stdin
          hack/capture-images.sh "${REGISTRY}"
